{"data": [{"id": 256, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/comment/add", "casename": "test_android_comment_add", "casepath": "case_X_API.case_comment.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓添加好友\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 234}, {"id": 257, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/comment/barrage", "casename": "test_android_comment_barrage", "casepath": "case_X_API.case_comment.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓添加好友\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 180}, {"id": 258, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/comment/list", "casename": "test_android_comment_list", "casepath": "case_X_API.case_comment.cases", "result": "fail", "consoleinfo": "########## RESULT OF \"安卓添加好友\" ##########\n执行冒烟测试。。。\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['commentid']\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['userid']\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['isself']\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['nickname']\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['img']\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['createline']\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['title']\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['nowtime']\n结构异常or数据缺失:不存在的键：['data']['list'][0]['target']['status']", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 33, in runtest\n    assert len(cmp_res.frame_cmpare_result) == 0\nAssertionError\n", "cost": 161}, {"id": 259, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/contact/intimatelist", "casename": "test_android_contact_intimatelist", "casepath": "case_X_API.case_contact.cases", "result": "fail", "consoleinfo": "########## RESULT OF \"通讯录亲密好友\" ##########\n执行冒烟测试。。。\n未知异常:实际数据不是list:['data']", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 33, in runtest\n    assert len(cmp_res.frame_cmpare_result) == 0\nAssertionError\n", "cost": 149}, {"id": 260, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "", "casename": "test_android_contact_invitelist", "casepath": "case_X_API.case_contact.cases", "result": "err", "consoleinfo": "", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 9, in runtest\n    req_res = fun(*args)\n  File \"E:\\devspace\\Xproject\\cases\\case_X_API\\case_contact.py\", line 49, in test_android_contact_invitelist\n    res = ContactUtils.contact_invitelist(self.request, content)\nNameError: name 'content' is not defined\n", "cost": 0}, {"id": 261, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/contact/upload", "casename": "test_android_contact_upload", "casepath": "case_X_API.case_contact.cases", "result": "err", "consoleinfo": "Expecting value: line 1 column 1 (char 0)\n接口数据获取异常", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 26, in runtest\n    raise ConnectionError('未得到预期格式结果')\nConnectionError: 未得到预期格式结果\n", "cost": 1052}, {"id": 262, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/friend/add", "casename": "test_android_friend_add", "casepath": "case_X_API.case_friend.cases", "result": "err", "consoleinfo": "Expecting value: line 1 column 1 (char 0)\n接口数据获取异常", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 26, in runtest\n    raise ConnectionError('未得到预期格式结果')\nConnectionError: 未得到预期格式结果\n", "cost": 205}, {"id": 263, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/friend/delete", "casename": "test_android_friend_add_delete", "casepath": "case_X_API.case_friend.cases", "result": "fail", "consoleinfo": "Expecting value: line 1 column 1 (char 0)\n########## RESULT OF \"安卓好友添加删除数据测试\" ##########\n执行全数据比对。。。\n未知异常:实际数据不是dict:['add_res']", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 38, in runtest\n    assert len(cmp_res.frame_cmpare_result) == len(cmp_res.data_compare_result) == 0\nAssertionError\n", "cost": 909}, {"id": 264, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/friend/delete", "casename": "test_android_friend_delete", "casepath": "case_X_API.case_friend.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓删除好友\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 193}, {"id": 265, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/friend/add", "casename": "test_android_friend_list", "casepath": "case_X_API.case_friend.cases", "result": "pass", "consoleinfo": "Expecting value: line 1 column 1 (char 0)\nExpecting value: line 1 column 1 (char 0)\nExpecting value: line 1 column 1 (char 0)\nExpecting value: line 1 column 1 (char 0)\n########## RESULT OF \"安卓好友列表数据测试\" ##########\n执行全数据比对。。。\n对比成功", "errinfo": "", "cost": 1070}, {"id": 266, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/create", "casename": "test_android_group_create", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓建群接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 358}, {"id": 267, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/info", "casename": "test_android_group_info", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓群信息接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 153}, {"id": 268, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/invite", "casename": "test_android_group_invite", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓群邀请接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 151}, {"id": 269, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/join", "casename": "test_android_group_join", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓加群接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 411}, {"id": 270, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/joinedlist", "casename": "test_android_group_joinedlist", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓群成员接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 162}, {"id": 271, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/kick", "casename": "test_android_group_kick", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓群踢人接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 154}, {"id": 272, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/memberlist", "casename": "test_android_group_memberlist", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓群用户列表接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 166}, {"id": 273, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/quit", "casename": "test_android_group_quit", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓退群接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 349}, {"id": 274, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "", "casename": "test_android_group_savethumb", "casepath": "case_X_API.case_group.cases", "result": "err", "consoleinfo": "", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 9, in runtest\n    req_res = fun(*args)\n  File \"E:\\devspace\\Xproject\\cases\\case_X_API\\case_group.py\", line 58, in test_android_group_savethumb\n    res = GroupUtils.group_savethumb(self.request, groupid=88, thumbdir=img)\n  File \"E:\\devspace\\Xproject\\utils\\XGroupUtils.py\", line 44, in group_savethumb\n    with open(thumbdir, 'rb') as f:\nFileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\\\\\cover.jpg'\n", "cost": 0}, {"id": 275, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/group/update", "casename": "test_android_group_update", "casepath": "case_X_API.case_group.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓更新群info接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 154}, {"id": 276, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/message/friendnew", "casename": "test_android_message_friendnew", "casepath": "case_X_API.case_message.cases", "result": "fail", "consoleinfo": "########## RESULT OF \"新好友查看接口\" ##########\n执行冒烟测试。。。\n结构异常or数据缺失:不存在的下标：['data']['list'][0]", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 33, in runtest\n    assert len(cmp_res.frame_cmpare_result) == 0\nAssertionError\n", "cost": 154}, {"id": 277, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/user/detail", "casename": "test_android_user_detail", "casepath": "case_X_API.case_user.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓用户detail接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 159}, {"id": 278, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/user/getcaptcha", "casename": "test_android_user_get_captcha", "casepath": "case_X_API.case_user.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓用户info接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 385}, {"id": 279, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/user/info", "casename": "test_android_user_info", "casepath": "case_X_API.case_user.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓用户info接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 147}, {"id": 280, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "", "casename": "test_android_user_savecover", "casepath": "case_X_API.case_user.cases", "result": "err", "consoleinfo": "", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 9, in runtest\n    req_res = fun(*args)\n  File \"E:\\devspace\\Xproject\\cases\\case_X_API\\case_user.py\", line 93, in test_android_user_savecover\n    res = UserUtils.user_savecover(self.request, coverdir=img)\n  File \"E:\\devspace\\Xproject\\utils\\XUserUtils.py\", line 81, in user_savecover\n    with open(coverdir, 'rb') as f:\nFileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\\\\\cat.jpg'\n", "cost": 0}, {"id": 281, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/user/saveinfo", "casename": "test_android_user_saveinfo", "casepath": "case_X_API.case_user.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓用户saveinfo接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 718}, {"id": 282, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "", "casename": "test_android_user_savethumb", "casepath": "case_X_API.case_user.cases", "result": "err", "consoleinfo": "", "errinfo": "Traceback (most recent call last):\n  File \"D:\\softinstall\\Anaconda3\\lib\\site-packages\\Tclass\\ResultDecorator.py\", line 9, in runtest\n    req_res = fun(*args)\n  File \"E:\\devspace\\Xproject\\cases\\case_X_API\\case_user.py\", line 84, in test_android_user_savethumb\n    res = UserUtils.user_savethumb(self.request, thumbdir=img)\n  File \"E:\\devspace\\Xproject\\utils\\XUserUtils.py\", line 60, in user_savethumb\n    with open(thumbdir, 'rb') as f:\nFileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\\\\\cover.jpg'\n", "cost": 0}, {"id": 283, "no": 1531451295, "platform": "QA", "service": "X_API", "uri": "/android/user/videolist", "casename": "test_android_user_videolist", "casepath": "case_X_API.case_user.cases", "result": "pass", "consoleinfo": "########## RESULT OF \"安卓用户视频列表接口\" ##########\n执行冒烟测试。。。\n对比成功", "errinfo": "", "cost": 161}]}